name: Publish
on:
  workflow_dispatch
#  release:
#    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/setup-gradle@v3
        with:
          gradle-version: wrapper
          arguments: build publishAllPublicationsToOSSRHRepository
    env:
      ORG_GRADLE_PROJECT_OSSRHUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_OSSRHPassword: ${{ secrets.OSSRH_TOKEN }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}